version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: America/Lima
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.1
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.29.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.5
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  - dependency-name: react-dom
    versions:
    - 16.13.0
  - dependency-name: "@storybook/addon-console"
    versions:
    - 1.2.2
